<?php
  session_start();

  if($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST['ID'];
    $password = $_POST['PW'];

/*if(id and passwords are matched) {*/

  header('Location:login.php');
// } 
   
  } else {
?>
    <script
    src = "http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js">
    </script>
    <div class = "row" id = "undertopbar">
        <div class = "small-6 columns" id = "textlinks">
            >
            <a href = "home">Categories</a>  > 
            <a href = "state">States</a>  >  
            <a href = "city">Cities</a>
        </div>
        <div class = "small-6 columns" id="inputs">
            <div class = "small-8 columns" id = "form">
                <form ng-app = "myApp" name = "myform" ng-submit="submit()" ng-controller="myCtrl">
                    <div class = "small-6 columns" id = "searchdiv"> 
                        <input type="text" ng-model = "searchterm" name = "searchterm" class = "Search" id = "searchbox" placeholder="Search in City"/>
                        <input type="submit" id = "enter"/>
                    </div>

                    <div class = "small-6 columns" id = "zipdiv">
                        <input type="text" ng-model = "zipcode" ng-pattern = "/^\d{5}$/" ng-change = "change()" name = "zipcode" class = "Zipcode" id = "zipcodebutton" placeholder="Enter Zip Code" />
                        <span id = "validzipcode" ng-show = "submitted && !changed && myform.zipcode.$error.pattern">Invalid Zipcode</span>
                        <input type="submit" id = "enter"/>
                    </div>
                </form>
            </div>

        <script>
        var myapp = angular.module('myApp',[]);
        myapp.controller('myCtrl', ['$scope', function($scope){
            $scope.submit = function(){
                $scope.submitted = true;
                $scope.changed = false;
                if ($scope.searchterm){
                    var searchterm = $scope.searchterm;
                    $scope.searchterm = '';
                    $scope.submitted = false;
                    console.log(searchterm);
                }
                if ($scope.zipcode){
                    $scope.submitted = false;
                    var zipcode = $scope.zipcode;
                    console.log(zipcode);
                }
            }
            $scope.change = function(){
                $scope.changed = true;
            }
        }]);
        </script>

            <div class = "small-4 columns" id = "filter">
                <a href="#" class="button tiny" id = "filterbutton" data-dropdown="drop">Filter by Distance</a>
                    <ul id="drop" class="small f-dropdown" data-dropdown-content>
                        <li><a href="#">This is a link</a></li>
                        <li><a href="#">This is another</a></li>
                        <li><a href="#">Yet another</a></li>
                    </ul>
            </div>
        </div>
    </div>
    <div class = "row" id = "allpostsrow">
        <div class="callout panel" id = "allpostspanel">
             <?php
                 class Post
                 {
                     public $Title;
                     public $Description;
                 }
  
                 $First = new Post();
                 $First->Title = 'First';
                 $First->Description = "I'm first post";

                 $Second = new Post();
                 $Second->Title = 'Second';
                 $Second->Description = "I'm second post";

                 $Posts = array($First, $Second);

                 foreach($Posts as $post){
                     echo
                     '<div class = "row" id = "postpanel">
                         <div class = small-1 columns" id = "thumbnail">
                             <a class = "th" id = "thumbimg" role = "button" aria-label = "Thumbnail" href = "#" data-reveal-id = "post-popup">
                                 <img aria-hidden=true src="https://lh3.googleusercontent.com/-NYmBRZN0E7U/AAAAAAAAAAI/AAAAAAAAACI/VsA9fnrvtu4/photo.jpg?sz=50"/>
                             </a>
                             <div id="post-popup" class = "reveal-modal" data-reveal aria-labelledby = "popup-title" aria-hidden = "true" role = "dialog" href = "#">
                                 <h2 id= "popup-title">Popup for post</h2>
                                 <a class = "close-reveal-modal" aria-label = "Close">&#215;</a>
                             </div>
                         </div>
                         <div class = "small-11 columns" id = "description">
                             <a href = "#" data-reveal-id = "post-popup">' . $post->Title .'</a>
                             <br>' . $post->Description . '
                         </div>
                      </div>';
                 } 
             ?>
        </div>
    </div>
<?php 
  }
?>
