<link rel="stylesheet" href="../css/postpage.css" />
     <div class = "row" id = "undertopbar">
        <div class = "small-6 columns" id = "textlinks">
            >
            <a href = "home">Categories</a>  > 
            <a href = "state">States</a>  >  
            <a href = "city">Cities</a>
        </div>
        <div class = "small-6 columns" id="inputs">
            <div class = "small-8 columns" id = "form">
                <form ng-app = "myApp" name = "myform" ng-submit="submit()" ng-controller="myCtrl">
                    <div class = "small-6 columns" id = "searchdiv"> 
                        <input type="text" ng-model = "searchterm" name = "searchterm" class = "Search" id = "searchbox" placeholder="Search in City"/>
                        <input type="submit" id = "enter"/>
                    </div>

                    <div class = "small-6 columns" id = "zipdiv">
                        <input type="text" ng-model = "zipcode" ng-pattern = "/^\d{5}$/" ng-change = "change()" name = "zipcode" class = "Zipcode" id = "zipcodebutton" placeholder="Enter Zip Code" />
                        <span id = "validzipcode" class = "ng-cloak" ng-show = "submitted && !changed && myform.zipcode.$error.pattern">Invalid Zipcode</span>
                        <input type="submit" id = "enter"/>
                    </div>
                </form>
            </div>

        <script>
        var myapp = angular.module('myApp',[]);
        myapp.controller('myCtrl', ['$scope', function($scope){
            $scope.submit = function(){
                $scope.submitted = true;
                $scope.changed = false;
                if ($scope.searchterm){
                    var searchterm = $scope.searchterm;
                    $scope.searchterm = '';
                    $scope.submitted = false;
                    console.log(searchterm);
                }
                if ($scope.zipcode){
                    $scope.submitted = false;
                    var zipcode = $scope.zipcode;
                    console.log(zipcode);
                }
            }
            $scope.change = function(){
                $scope.changed = true;
            }
        }]);
        </script>
            <div class = "small-4 columns" id = "filter">
                <a href="#" class="button tiny" id = "filterbutton" data-dropdown="drop">Filter by Distance</a>
                    <ul id="drop" class="small f-dropdown" data-dropdown-content>
                        <li><a href="#">This is a link</a></li>
                        <li><a href="#">This is another</a></li>
                        <li><a href="#">Yet another</a></li>
                    </ul>
            </div>
        </div>
    </div> 

<!-- Orbit Container -->
<div class = "row">
<h3>Title</h3>
</div>
<div class = "row">
    <div class="small-8 small-centered columns">
        <ul class="example-orbit" data-orbit data-options="timer:false;">

            <li>
                <div class = "image-container">
                    <img src="http://www.unc.edu/tlim/sakai_pilot_blog/www.wiinintendo.net/wp-content/uploads/2009/01/1up_wallpaper_by_arcwing-600x480.jpg" id = "img" alt="slide 1" />
                    <div class="orbit-caption">
                        Caption One.
                    </div>     
                </div> 
            </li>
            <li>
                <div class = "image-container">
                    <img src="http://mrdeyo.com/whiteboard/wp-content/uploads/2013/08/feather-white-500x700.jpg" alt="slide 2" id = "img" />
                    <div class="orbit-caption">
                        Caption Two.
                    </div>
                </div>
            </li>
            <li>
                <div class = "image-container">
                    <img src="http://www.telemet.com/wp-content/uploads/2009/07/lang_inicio-700x300.jpg" alt="slide 3" id = "img" />
                    <div class="orbit-caption">
                        Caption Three.
                    </div>
                </div>
            </li>

        </ul>
    </div>
</div>
<p>Descriptions</p>
    <!-- Foundation Scripts -->
    <script src="../js/vendor/jquery.js"></script>
  	<script src="../js/foundation.min.js"></script>
    <script>
		$(document).foundation();
	</script>
