<?php
  session_start();

  if($_SERVER["REQUEST_METHOD"] == "POST") {
    $username = $_POST['ID'];
    $password = $_POST['PW'];

/*if(id and passwords are matched) {*/

  header('Location:login.php');
// } 
   
  } else {
?>    <script
    src = "http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js">
    </script>
    <div class = "row" id = "undertopbar">
        <div class = "small-6 columns" id = "textlinks">
            >
            <a href = "home">Categories</a>  > 
            <a href = "state">States</a>  >  
            <a href = "city">Cities</a>
        </div>
        <div class = "small-6 columns" id="inputs">
            <div class = "small-8 columns" id = "form">
                <form ng-app = "myApp" name = "myform" ng-submit="submit()" ng-controller="myCtrl">
                    <div class = "small-6 columns" id = "searchdiv"> 
                        <input type="text" ng-model = "searchterm" name = "searchterm" class = "Search" id = "searchbox" placeholder="Search in City"/>
                        <input type="submit" id = "enter"/>
                    </div>

                    <div class = "small-6 columns" id = "zipdiv">
                        <input type="text" ng-model = "zipcode" ng-pattern = "/^\d{5}$/" ng-change = "change()" name = "zipcode" class = "Zipcode" id = "zipcodebutton" placeholder="Enter Zip Code" />
                        <span id = "validzipcode" ng-show = "submitted && !changed && myform.zipcode.$error.pattern">Invalid Zipcode</span>
                        <input type="submit" id = "enter"/>
                    </div>
                </form>
            </div>

        <script>
        var myapp = angular.module('myApp',[]);
        myapp.controller('myCtrl', ['$scope', function($scope){
            $scope.submit = function(){
                $scope.submitted = true;
                $scope.changed = false;
                if ($scope.searchterm){
                    var searchterm = $scope.searchterm;
                    $scope.searchterm = '';
                    $scope.submitted = false;
                    console.log(searchterm);
                }
                if ($scope.zipcode){
                    $scope.submitted = false;
                    var zipcode = $scope.zipcode;
                    console.log(zipcode);
                }
            }
            $scope.change = function(){
                $scope.changed = true;
            }
        }]);
        </script>
            <div class = "small-4 columns" id = "filter">
                <a href="#" class="button tiny" id = "filterbutton" data-dropdown="drop">Filter by Distance</a>
                    <ul id="drop" class="small f-dropdown" data-dropdown-content>
                        <li><a href="#">This is a link</a></li>
                        <li><a href="#">This is another</a></li>
                        <li><a href="#">Yet another</a></li>
                    </ul>
            </div>
        </div>
    </div> 
<!-- Orbit Container -->
<link rel="stylesheet" href="../css/postpage.css" />
<div class = "row">
<h3>Title</h3>
</div>
<div class = "row">
    <div class="small-8 small-centered columns">
        <ul class="example-orbit" data-orbit data-options="timer:false;">
            <li>
                <img src="http://www.blackberry-wallpapers.com/uploads/allimg/110513/2-1105131555130-L.jpg" alt="slide 1" />
                <div class="orbit-caption">
                    Caption One.
                </div>
            </li>
            <li class="active">
                <img src="http://www.solidbackgrounds.com/images/640x480/640x480-light-pink-solid-color-background.jpg" alt="slide 2" />
                <div class="orbit-caption">
                    Caption Two.
                </div>
            </li>
            <li>
            <img src="http://www.solidbackgrounds.com/images/640x480/640x480-columbia-blue-solid-color-background.jpg" alt="slide 3" />
                <div class="orbit-caption">
                    Caption Three.
                </div>
            </li>
        </ul>
    </div>
</div>
<p>Descriptions</p>
    <!-- Foundation Scripts -->
    <script src="../js/vendor/jquery.js"></script>
  	<script src="../js/foundation.min.js"></script>
    <script>
		$(document).foundation();
	</script>
 


<?php 
  }
?>
