    <link rel="stylesheet" href="../css/postlist.css" />
    <link rel="stylesheet" href="../css/postpage.css" />
    <div class = "row" id = "undertopbar">
        <div class = "small-6 columns" id = "textlinks">
            <a href = "home">Categories</a>  > 
            <a href = "state">States</a>  >  
            <a href = "city">Cities</a>
        </div>
        <div class = "small-6 columns" id="inputs">
            <div class = "small-8 columns" id = "form">
                <form ng-app = "myApp" name = "myform" ng-submit="submit()" ng-controller="myCtrl">
                    <div class = "small-6 columns" id = "searchdiv"> 
                        <input type="text" ng-model = "searchterm" name = "searchterm" class = "Search" id = "searchbox" placeholder="Search in City"/>
                        <input type="submit" id = "enter"/>
                    </div>

                    <div class = "small-6 columns" id = "zipdiv">
                        <input type="text" ng-model = "zipcode" ng-pattern = "/^\d{5}$/" ng-change = "change()" name = "zipcode" class = "Zipcode" id = "zipcodebutton" placeholder="Enter Zip Code" />
                        <span id = "validzipcode" class = "ng-cloak" ng-show = "submitted && !changed && myform.zipcode.$error.pattern">Invalid Zipcode</span>
                        <input type="submit" id = "enter"/>
                    </div>
                </form>
            </div>

        <script>
        var myapp = angular.module('myApp',[]);
        myapp.controller('myCtrl', ['$scope', function($scope){
            $scope.submit = function(){
                $scope.submitted = true;
                $scope.changed = false;
                if ($scope.searchterm){
                    var searchterm = $scope.searchterm;
                    $scope.searchterm = '';
                    $scope.submitted = false;
                    console.log(searchterm);
                }
                if ($scope.zipcode){
                    $scope.submitted = false;
                    var zipcode = $scope.zipcode;
                    console.log(zipcode);
                }
            }
            $scope.change = function(){
                $scope.changed = true;
            }
        }]);
        </script>

            <div class = "small-4 columns" id = "filter">
                <a href="#" class="button tiny" id = "filterbutton" data-dropdown="drop">Filter by Distance</a>
                    <ul id="drop" class="small f-dropdown" data-dropdown-content>
                        <li><a href="#">This is a link</a></li>
                        <li><a href="#">This is another</a></li>
                        <li><a href="#">Yet another</a></li>
                    </ul>
            </div>
        </div>
    </div>
    <div class = "row" id = "allpostsrow" style="margin-top:20px">
        <?php foreach($posts as $post): ?>
        <div style="border:1px solid #999"></div>
        <div class="" id = "allpostspanel" style="margin:20px">
                <div class = "row" id = "postpanel">
                    <div class = small-1 columns" id = "thumbnail">
                        <a class = "th" id = "thumbimg" role = "button" aria-label = "Thumbnail" href = "#" data-reveal-id = "post-popup">
                            <img aria-hidden=true src="<?php echo $post->post_thumb;?>"/>
                        </a>
                        <div id="post-popup-<?php echo $post->post_id;?>" class = "reveal-modal" data-reveal aria-labelledby = "popup-title" aria-hidden = "true" role = "dialog" href = "#">
                            <h2 id= "popup-title"><?php echo $post->post_title;?></h2>
                            <ul class="example-orbit" data-orbit data-options="timer:false;">
                                <li>
                                    <div class = "image-container">
                                        <img src="<?php echo $post->post_thumb;?>" id = "img" alt="slide 1" />
                                        <div class="orbit-caption">
                                            caption one.
                                        </div>     
                                    </div> 
                                </li>
                                <li>
                                    <div class = "image-container">
                                        <img src="http://mrdeyo.com/whiteboard/wp-content/uploads/2013/08/feather-white-500x700.jpg" alt="slide 2" id = "img" />
                                        <div class="orbit-caption">
                                            caption two.
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class = "image-container">
                                        <img src="http://www.telemet.com/wp-content/uploads/2009/07/lang_inicio-700x300.jpg" alt="slide 3" id = "img" />
                                        <div class="orbit-caption">
                                            caption three.
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <div style="margin-top:10px"><?php echo  $post->post_body; ?></div>
                            <a class = "close-reveal-modal" aria-label = "Close">&#215;</a>
                        </div>
                    </div>
                    <div class = "small-11 columns" id = "description">
                        <a href = "#" data-reveal-id = "post-popup-<?php echo $post->post_id;?>"><?php echo $post->post_title;?></a>
                        <br><?php echo  $post->post_head; ?>
                    </div>
                 </div>
        </div>
        <?php endforeach; ?>
    </div>
