<?php echo $this->doctype(); ?>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vizisells.com</title>
    <link rel="stylesheet" href="../css/foundation.css" />
    <link rel="stylesheet" href="../css/vz/layout.css" />
    <script src="../js/vendor/angular.min.js"></script>
    <script src="../js/vendor/modernizr.js"></script>
    <script src="../js/vendor/jquery.js"></script>
  </head>
  <body>
<div class = "row logo-bar">
  <div class ="large-6 columns logo">
    <a href='../'><img src='../img/index/logo.png' /></a>
	</div>
  <div class ="large-6 columns bar">
    <nav class="top-bar" data-topbar role="navigation">

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="left">
        <li><a class="top-bar-left" href="../">HOME</a></li>
        <li class="divider"></li>
        <li><a href="#" data-reveal-id="myModal">SIGN UP</a></li>
        <li class="divider"></li>
        <li><a class="top-bar-right"href="#">ABOUT US</a></li>
    </ul>
  </section>
<!--Pop up -->
<!-- Reveal Modals begin -->
<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog" style="top:175px;display:none;visibility:hidden;opacity:1;">
  <h2 class="small-12 columns" id="firstModalTitle">Sign in</h2>

<!--Log in form-->
<form action = "vizi-admin.php" method="POST">
    <div class="row">
		<div class = "small-6">
        <div class="small-12 columns">
          <input type="text" name="ID" placeholder="Email address" />       
          <input type="password" name="PW" placeholder="Password" />
   		</div>
	</div>
    </div>

	<div class="row">
		<div class = "small-6">
			<div class = "small-6 columns">
				<input type="checkbox" name="Signed" value="StaySignedIn">Stay signed in  
			</div>
			<div class = "small-6 columns">
				Forgot Password?
			</div>
		</div>
	</div>

	<div class="row">
		<div class="small-6 columns">
			Uncheck on public devices.
		</div>
	</div>

    <div class="row">
        <div class = "large-6 medium-6 small-6 columns">
        <!--This log in URL will lead to User page -->
        <a href="../" class="button small-12 Login">Sign In</a>
    	</div>
    </div>

	<div class ="row">
		<div class = "small-6">
			<div class = "small-12 columns">
				Not a member yet? <a href="../">Get a Vizisells ID</a>
			</div>
		</div>
	</div>	
</form>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>


<div id="secondModal" class="reveal-modal" data-reveal aria-labelledby="secondModalTitle" aria-hidden="true" role="dialog">
  <h2 id="secondModalTitle">This is a Sign up page</h2>
  <p>Sign up Please!!!</p>
  <!--This is where the sign up page will be designed -->
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

    <!-- Sign In changes to My account once signed in.
      <li class="has-dropdown">
        <a href="#">My Account</a>
        <ul class="dropdown">
          <li><a href="#">User Profile</a></li>
        </ul>
      </li>
    -->
</nav>
</div></div>
        <div class="container">
            <?php echo $this->content; ?>
            <footer id = "footer">
            <hr>
                <div class="row">
                    <div class="columns"> 
                        <p>&copy; 2015 - <?php echo date('Y') ?> by ©Vizisells.com. <?php echo $this->translate('All rights reserved.') ?></p>
                    </div>
                </div>
            </footer>
        </div> <!-- /container -->
        <script src="../js/vendor/jquery.js"></script>
        <script src="../js/foundation.min.js"></script> 
        <script>
            $(document).foundation();
        </script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>

