<?php 
  $categories = array("Activities","Cars","Education","Electronics",
                      "Fashion","Food","Home Goods","House on sale",
                      "Jobs","Meet Ups","Merchandise","Rent","Services",
                      "Others");
?>
<link rel="stylesheet" href="../css/vz/index.css" />
<script src="../js/vz/index.js"></script>
  <div class='row fullWidth'>
        <div class='large-12 medium-12 small-12 columns'>
            <ul class="small-block-grid-5">
              <li class='sideli'>
              <div class = "half-width categoryDiv">
				<p class = 'text'>Services</p>
				<p class='description'>Looking to find a plumber? dentist? electrician? etc... Find them here.</p>
			<a href='../state/list?category=services'><img class ='pic' src='../img/index/services.jpg'/></a>
              </div>
              </li>
              <li class ='centerli'>
              <div class ='center-width'>
                <img src='../img/index/words.jpg'/>
              </div>
              </li>
              <li class='centerli'>
              <div class = "center-width categoryDiv back-orange">
				<p class = 'text'>Car</p>
                <a href='../state/list?category=car'><img class = 'pic' src='../img/index/car.jpg'/></a>
              </div>
              </li>
              <li class='centerli'>
              <div  class = "center-width categoryDiv back-yellow">
				<p class = 'text'>Electronics</p>
                <a href='../state/list?category=electronics'><img class = 'pic' src='../img/index/electronics.jpg'/></a>
              </div>
              </li>
              <li class='sideli'>
              <div class = 'half-width categoryDiv'>
				<p class = 'text'>Food</p>
                <p class='description'>Hungry? Find your next meal here. Local restaurants with customer ratings</p>
				<a href='../state/list?category=food'><img class = 'pic' src='../img/index/food.jpg'/></a>
              </div>
              </li>
            </ul>
        </div>
  </div>
  <div class='row fullWidth'>
        <div class='large-12 medium-12 small-12 columns'>
        <ul class="small-block-grid-5">
          <li class='sideli'>
          <div class = 'half-width categoryDiv'>
			<p class= 'text'>Education</p>	
			<p class='description'>Come in and get more local education. Meet people that share your intereset and learn together.</p>
            <a href='../state/list?category=education'><img class = 'pic' src='../img/index/education.jpg'/></a>
          </div>
          </li>
          <li class='centerli'>
          <div class = 'center-width categoryDiv back-yellow'>
			<p class = 'text'>For Sale</p>
            <a href='../state/list?category=house'><img class = 'pic' src='../img/index/house.jpg'/></a>
          </div>
          </li>
          <li class='centerli'>
          <div class = 'center-width categoryDiv back-green'>
			<p class='text'>Jobs</p>
            <a href='../state/list?category=jobs'><img class = 'pic' src='../img/index/jobs.jpg'/></a>
          </div>
          </li>
          <li class='centerli'>
          <div class = 'center-width categoryDiv back-orange'>
			<p class='text'>Kitchen &amp; Furniture</p>
            <a href='../state/list?category=homegoods'><img class = 'pic' src='../img/index/housegood.png'/></a>
          </div>
          </li>
          <li class='sideli'>
          <div class = 'half-width categoryDiv'>
			<p class='text'>Let's Meet</p>
			<p class='description'>Meet peers which like what you like and want to get together to share new ideas. Start a new group and meet locally.</p>
            <a href='../state/list?category=meetup'><img class = 'pic' src='../img/index/meet.jpg'/></a>
          </div>
          </li>
        </ul>
        </div>
  </div>
  <div class='row fullWidth'>
        <div class='large-12 medium-12 small-12 columns'>
        <ul class="small-block-grid-5">
          <li class='sideli'>
          <div class = 'half-width categoryDiv'>
			<p class = 'text'>Activities</p>
			<p class='description'>Looking to meet people that share your interest? Well, they are here. Join them and have fun.</p>
            <a href='../state/list?category=activity'><img class='pic' src='../img/index/activity.jpg'/></a>
          </div>
          </li>
          <li class='centerli'>
          <div class = 'center-width categoryDiv back-orange'>
			<p class='text'>Merchandise</p>
            <a href='../state/list?category=merchandise'><img class = 'pic' src='../img/index/merchandise.jpg'/></a>
          </div>
          </li>
          <li class='centerli'>
          <div class = 'center-width categoryDiv back-yellow'>
			<p class='text'>For Rent</p>
            <a href='../state/list?category=rent'><img class = 'pic' src='../img/index/rent.jpg'/></a>
          </div>
          </li>
          <li class='centerli'>
          <div class = 'center-width categoryDiv back-green'>
			<p class='text'>Fashion</p>
            <a href='../state/list?category=fashion'><img class = 'pic' src='../img/index/fashion.jpg'/></a>
          </div>
          </li>
          <li class='sideli'>
          <div class = 'half-width categoryDiv'>
			<p class='text'>Others</p>
			<p class='description'>Still haven't found what you are looking for? Try looking here.</p>
            <a href='../state/list?category=others'><img class = 'pic' src='../img/index/others.jpg'/></a>
          </div>
          </li>
        </ul>
        </div>
  </div>
